# Generated by Django 4.2.4 on 2023-09-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogLLM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('task_type', models.CharField(default=None, max_length=32, null=True)),
                ('question', models.TextField()),
                ('context', models.TextField(default=None, null=True)),
                ('answer', models.TextField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogLLMState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('state', models.CharField(max_length=20)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='llm.logllm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
