# Generated by Django 4.2.4 on 2023-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_session_logllm_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("date", models.DateTimeField(verbose_name="시세 날짜")),
                ("highest_price", models.FloatField(default=0)),
                ("lowest_price", models.FloatField(default=0)),
                ("close_price", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
