# Generated by Django 4.2.4 on 2023-10-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0003_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="name",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
