version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: llm
#      MYSQL_DATABASE: llm
#      MYSQL_USER:
#      MYSQL_PASSWORD: mypassword

  django:
    build:
      context: ../
      dockerfile: ops/Dockerfile
    ports:
      - "80:80"
#    volumes:
#      - ./:./
    depends_on:
      - db

volumes:
  db_data: